# Generated by Django 6.0.7 on 2026-07-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='original_author_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='original_author_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
