# Generated by Django 6.0.7 on 2026-07-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_merge_20260722_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
