# Generated by Django 6.0.7 on 2026-07-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_rename_is_notified_transferrequest_requester_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
