# Generated by Django 6.0.7 on 2026-07-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_collaboration_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='original_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
